tools: fix license header check
Signed-off-by: Jonathan Boulle <jonathanboulle@gmail.com>

diff --git a/.tool/check-license b/.tool/check-license
--- a/.tool/check-license
+++ b/.tool/check-license
@@ -7,7 +7,10 @@ set -o pipefail
 ret=0
 
 for file in $(find . -type f -iname '*.go' ! -path './vendor/*'); do
-	(head -n3 "${file}" | grep -Eq "(Copyright|generated|GENERATED)") || (echo "${file}:missing license header" && ret=1)
+	if ! head -n3 "${file}" | grep -Eq "(Copyright|generated|GENERATED)"; then
+		echo "${file}:missing license header"
+		ret=1
+	fi
 done
 
 exit $ret
